---
db_name: showyourheart
db_user: showyourheart
db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61353130616533343566356332386135373836356336363134383633363133623866366366633361
          3063383133386332383439346465396561626633636138330a623730383233306634303461613565
          34333332353465313239653538626539376662363465313530653331623362646161363637643862
          3135306566393930320a633735663562643633643463653234663437356461333466396234633730
          37646233653261363166343533313338313439313030393061623934373837343965
